version: '3.3'

services:
  checkout_server:
    build:
      context: ./checkout_server
      dockerfile: Dockerfile
      args:
        APP_NAME: checkout_server
    environment:
      - RAILS_ENV=development
    volumes:
      - ./checkout_server:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  proxy_server:
    build:
      context: ./proxy_server
      dockerfile: Dockerfile
      args:
        APP_NAME: proxy_server
    environment:
      - RAILS_ENV=development
    volumes:
      - ./proxy_server:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
