version: '3.3'

services:
  checkout_server:
    stdin_open: true
    tty: true
    build:
      context: ./checkout_server
      dockerfile: Dockerfile
      args:
        APP_NAME: checkout_server
    environment:
      - RAILS_ENV=development
    volumes:
      - ./checkout_server:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      internal:
        aliases:
          - checkout-server

  proxy_server:
    stdin_open: true
    tty: true
    build:
      context: ./proxy_server
      dockerfile: Dockerfile
      args:
        APP_NAME: proxy_server
    environment:
      - RAILS_ENV=development
    volumes:
      - ./proxy_server:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq
    networks:
      internal:
        aliases:
          - proxy-server

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
volumes:
  bundle_path:

networks:
  internal:
