version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www/app
      - bundle_path:/bundle
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    networks:
      default:
      internal:
        aliases:
          - proxy-backend-server
    ports:
      - '3035:3035'
      - '5000:5000'
 
volumes:
  bundle_path:

networks:
  internal:
